### ISSUE TITLE
Партикли не убираются вместе с чипом

### ISSUE THREAD

**Issue by UAVXP** [l33tRS/E2Power#1]
В названии всё описано, собственно

**Comment by tengzl33t** [comment]
@UAVXP 
Они и не должны исчезать вместе с чипом, это партикли, а не голограммы.

**Comment by UAVXP** [comment]
@tengzl33t Абуз партиклями: можно наспаунить дохера партиклей, а затем удалить чип.
Или при тестировании, если перепутать параметры, к примеру

**Comment by 0Fox** [comment]
@UAVXP В игре есть ограничение в кол-ве партиклей.

**Comment by UAVXP** [comment]
@Zimon4eR Но, насколько я могу видеть, нет ограничения на их размер и продолжительность жизни
![20170328183353_1](https://cloud.githubusercontent.com/assets/3075683/24413818/4489f7da-13e5-11e7-921e-d4fbed89a64c.jpg)
![20170328183359_1](https://cloud.githubusercontent.com/assets/3075683/24413816/44835588-13e5-11e7-9e30-4df9b841e837.jpg)
Чип, ко времени снятия скриншотов выше, я уже удалил

**Comment by UAVXP** [comment]
А вот что бывает, если его оставить работающим.
Это дико залагивает клиент игры, если игрок смотрит в сторону партиклей. Я уже не говорю о том, что чем ближе он к ним - тем всё хуже и хуже FPS. И всё это достигается единственной строчкой. Мне кажется, следует ввести ограничение на максимальный размер партикля, если даже не удалять партикли вместе с удалением чипа. Представьте, что будет, если поместить эмиттер партиклей прямо перед EyePos игрока.
![image](https://cloud.githubusercontent.com/assets/3075683/24414553/65d6c3b2-13e7-11e7-83d5-ef64134726cc.png)

Даже если выставить ограничение количества партиклей в секунду на 5 - если находиться рядом с ними - выходит около 15 FPS и ощутимый input-лаг. Вот здесь всего 5 партиклей в секунду, и я стою прямо возле чипа, смотря в пол:
![image](https://cloud.githubusercontent.com/assets/3075683/24414848/333d9628-13e8-11e7-931d-00849d9ddb9f.png)

Более того - партикли ведь отрисовываются и через браши (снято уже спустя некоторое время после удаления чипа и под землёй, поэтому 50 FPS):
![image](https://cloud.githubusercontent.com/assets/3075683/24414451/1b3708bc-13e7-11e7-8131-44fe4a34e47e.png)

**Comment by 0Fox** [comment]
@UAVXP , если хочешь ограничить кол-во партиклей которое может спавнить игрок в секунду - можно использовать "wire_e2_maxParticlesPerSecond", значение 100 по дефолту.

Их размер на производительность не влияет, но лимиты я уменьшу.
Лимиты которые есть на партикли сейчас:
Кол-во партиклей которое может отображаться на клиенте одновременно - около 5к. (Тут уже лимит игры, а не е2п.)
Максимальная жизнь партикля - минута.
Стартовый и конечный размер - 3000, его я уменьшу.
