### ISSUE TITLE
Change E2 Functions to return Vector/Angle userdata

### ISSUE THREAD

**Issue by vurvdev** [l33tRS/E2Power#10]
This is an issue to warn that any functions that return the ``vector`` or ``angle`` E2 type will be broken if they aren't converted from returning lua tables of three numbers, for example ``{0, 0, 0}`` to instead returning the glua userdata ``Vector(0, 0, 0)`` or ``Angle(0, 0, 0)``.

This is part of an effort to ensure the amount of extensions broken by wiremod/wire#2399 is minimal.

**Comment by tengzl33t** [comment]
2e78d45ade9e8fa85bab8998f84f9b21bf6a4c91
No time for this.
