### ISSUE TITLE
Проблема с утоновкой e2p

### ISSUE THREAD

**Issue by ghost** [l33tRS/E2Power#4]
Помогите только как поставлю e2p на сервер как тут же это ошибка!
![image](https://user-images.githubusercontent.com/24373388/32417350-09191d04-c27a-11e7-9786-a6e573006621.png)
Куда я только не пытался поставить этот аддон на:
Debian 8.9.0 server
Ubuntu 16.04 server
и т.д.
Срочно HELP ME!!!

**Comment by 0Fox** [comment]
Обновил, проверь теперь

**Comment by ghost** [comment]
Все работает как надо спасибо!
