### ISSUE TITLE
Трабл с SetKeyValue

### ISSUE THREAD

**Issue by bewflast** [l33tRS/E2Power#8]
Привет, если есть возможность, пофиксите, пожалуйста, ent:setKeyValue()

При попытке сетнуть ключу "modelindex" значение "1", все клиенты крашатся
[Писал Фейспанчам](https://github.com/Facepunch/garrysmod-issues/issues/5207), теперь ждем, но вы сами понимаете, насколько это может там затянуться)

# Как повторить:
1. owner():setKeyValue("modelindex", 1) 
Вместо сущности овнера может быть любая другая

**Comment by tengzl33t** [comment]
#9 solved

**Comment by tengzl33t** [comment]
#9 solved
